vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        user_images:
            uri_prefix: /images/user_profile
            upload_destination: '%kernel.project_dir%/public/images/user_profile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        service_images:
            uri_prefix: /images/service
            upload_destination: '%kernel.project_dir%/public/images/service'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
