version: '3'

services:
  db:
    image: mysql
    container_name: db_project_event
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmni_project_event
    restart: always
    depends_on:
      - db
    ports:
      - 8083:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  www:
    build: docker
    container_name: www_project_event
    restart: always
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    ports:
      - "8002:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
