<?php

namespace ContainerV4SxvXG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_34cK6ZSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.34cK6ZS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.34cK6ZS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'demande' => ['privates', '.errored..service_locator.34cK6ZS.App\\Entity\\Demandes', NULL, 'Cannot autowire service ".service_locator.34cK6ZS": it needs an instance of "App\\Entity\\Demandes" but this type has been excluded in "config/services.yaml".'],
            'demandesRepository' => ['privates', 'App\\Repository\\DemandesRepository', 'getDemandesRepositoryService', true],
        ], [
            'demande' => 'App\\Entity\\Demandes',
            'demandesRepository' => 'App\\Repository\\DemandesRepository',
        ]);
    }
}
