<?php

namespace ContainerV4SxvXG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9ehO_9TService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9ehO.9T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9ehO.9T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'demandesRepository' => ['privates', 'App\\Repository\\DemandesRepository', 'getDemandesRepositoryService', true],
            'messageRepository' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'demandesRepository' => 'App\\Repository\\DemandesRepository',
            'messageRepository' => 'App\\Repository\\MessageRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
