<?php

namespace ContainerV4SxvXG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y8SFMjvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y8SFMjv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y8SFMjv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'service' => ['privates', '.errored..service_locator.Y8SFMjv.App\\Entity\\Service', NULL, 'Cannot autowire service ".service_locator.Y8SFMjv": it needs an instance of "App\\Entity\\Service" but this type has been excluded in "config/services.yaml".'],
            'serviceRepository' => ['privates', 'App\\Repository\\ServiceRepository', 'getServiceRepositoryService', true],
        ], [
            'service' => 'App\\Entity\\Service',
            'serviceRepository' => 'App\\Repository\\ServiceRepository',
        ]);
    }
}
