<?php

namespace ContainerV4SxvXG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WkT1BkyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wkT1Bky' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wkT1Bky'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'accredPro' => ['privates', '.errored..service_locator.wkT1Bky.App\\Entity\\AccreditationPro', NULL, 'Cannot autowire service ".service_locator.wkT1Bky": it needs an instance of "App\\Entity\\AccreditationPro" but this type has been excluded in "config/services.yaml".'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'user' => ['privates', '.errored..service_locator.wkT1Bky.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.wkT1Bky": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'accredPro' => 'App\\Entity\\AccreditationPro',
            'manager' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
