<?php

namespace ContainerV4SxvXG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2O3tjCKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2O3tjCK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2O3tjCK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'favoriRepository' => ['privates', 'App\\Repository\\FavoriRepository', 'getFavoriRepositoryService', true],
        ], [
            'favoriRepository' => 'App\\Repository\\FavoriRepository',
        ]);
    }
}
