<?php

namespace ContainerV4SxvXG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZQfguzgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zQfguzg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zQfguzg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'demandesRepository' => ['privates', 'App\\Repository\\DemandesRepository', 'getDemandesRepositoryService', true],
            'message' => ['privates', '.errored..service_locator.zQfguzg.App\\Entity\\Message', NULL, 'Cannot autowire service ".service_locator.zQfguzg": it needs an instance of "App\\Entity\\Message" but this type has been excluded in "config/services.yaml".'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'demandesRepository' => 'App\\Repository\\DemandesRepository',
            'message' => 'App\\Entity\\Message',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
