<?php

namespace ContainerV4SxvXG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OCL4gPlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OCL4gPl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OCL4gPl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evenement' => ['privates', '.errored..service_locator.OCL4gPl.App\\Entity\\Evenement', NULL, 'Cannot autowire service ".service_locator.OCL4gPl": it needs an instance of "App\\Entity\\Evenement" but this type has been excluded in "config/services.yaml".'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'evenement' => 'App\\Entity\\Evenement',
            'manager' => '?',
        ]);
    }
}
