<?php

namespace ContainerV4SxvXG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZAl2QiaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zAl2Qia' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zAl2Qia'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'discussion' => ['privates', '.errored..service_locator.zAl2Qia.App\\Entity\\Discussion', NULL, 'Cannot autowire service ".service_locator.zAl2Qia": it needs an instance of "App\\Entity\\Discussion" but this type has been excluded in "config/services.yaml".'],
        ], [
            'discussion' => 'App\\Entity\\Discussion',
        ]);
    }
}
