<?php

namespace ContainerV4SxvXG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O4H1MqHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O4H1MqH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O4H1MqH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'disponibilite' => ['privates', '.errored..service_locator.O4H1MqH.App\\Entity\\Disponibilite', NULL, 'Cannot autowire service ".service_locator.O4H1MqH": it needs an instance of "App\\Entity\\Disponibilite" but this type has been excluded in "config/services.yaml".'],
            'disponibiliteRepository' => ['privates', 'App\\Repository\\DisponibiliteRepository', 'getDisponibiliteRepositoryService', true],
        ], [
            'disponibilite' => 'App\\Entity\\Disponibilite',
            'disponibiliteRepository' => 'App\\Repository\\DisponibiliteRepository',
        ]);
    }
}
