<?php

namespace ContainerV4SxvXG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1my8QqUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1my8QqU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1my8QqU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'accreditationProRepository' => ['privates', 'App\\Repository\\AccreditationProRepository', 'getAccreditationProRepositoryService', true],
        ], [
            'accreditationProRepository' => 'App\\Repository\\AccreditationProRepository',
        ]);
    }
}
