<?php

namespace ContainerV4SxvXG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccreditationProService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wkT1Bky.App\Entity\AccreditationPro' shared service.
     *
     * @return \App\Entity\AccreditationPro
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.wkT1Bky": it needs an instance of "App\\Entity\\AccreditationPro" but this type has been excluded in "config/services.yaml".');
    }
}
