<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXP1gF3N\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXP1gF3N/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXP1gF3N.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXP1gF3N\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXP1gF3N\App_KernelDevDebugContainer([
    'container.build_hash' => 'XP1gF3N',
    'container.build_id' => '40cf47e5',
    'container.build_time' => 1684929844,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXP1gF3N');
