<?php

namespace ContainerXP1gF3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BdXYQZvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BdXYQZv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BdXYQZv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentaire' => ['privates', '.errored..service_locator.BdXYQZv.App\\Entity\\Commentaire', NULL, 'Cannot autowire service ".service_locator.BdXYQZv": it needs an instance of "App\\Entity\\Commentaire" but this type has been excluded in "config/services.yaml".'],
            'commentaireRepository' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService', true],
        ], [
            'commentaire' => 'App\\Entity\\Commentaire',
            'commentaireRepository' => 'App\\Repository\\CommentaireRepository',
        ]);
    }
}
