<?php

namespace ContainerXP1gF3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HDjc020Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hDjc020' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hDjc020'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'demande' => ['privates', '.errored..service_locator.hDjc020.App\\Entity\\Demandes', NULL, 'Cannot autowire service ".service_locator.hDjc020": it needs an instance of "App\\Entity\\Demandes" but this type has been excluded in "config/services.yaml".'],
            'disponibiliteRepository' => ['privates', 'App\\Repository\\DisponibiliteRepository', 'getDisponibiliteRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'demande' => 'App\\Entity\\Demandes',
            'disponibiliteRepository' => 'App\\Repository\\DisponibiliteRepository',
            'manager' => '?',
        ]);
    }
}
