<?php

namespace ContainerXP1gF3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RW_Jqr7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RW.Jqr7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RW.Jqr7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'demande' => ['privates', '.errored..service_locator.RW.Jqr7.App\\Entity\\Demandes', NULL, 'Cannot autowire service ".service_locator.RW.Jqr7": it needs an instance of "App\\Entity\\Demandes" but this type has been excluded in "config/services.yaml".'],
        ], [
            'demande' => 'App\\Entity\\Demandes',
        ]);
    }
}
