<?php

namespace ContainerXP1gF3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6H0D2AService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6H_0D2A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6H_0D2A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'demandesRepository' => ['privates', 'App\\Repository\\DemandesRepository', 'getDemandesRepositoryService', true],
            'disponibiliteRepository' => ['privates', 'App\\Repository\\DisponibiliteRepository', 'getDisponibiliteRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'service' => ['privates', '.errored..service_locator.6H_0D2A.App\\Entity\\Service', NULL, 'Cannot autowire service ".service_locator.6H_0D2A": it needs an instance of "App\\Entity\\Service" but this type has been excluded in "config/services.yaml".'],
        ], [
            'demandesRepository' => 'App\\Repository\\DemandesRepository',
            'disponibiliteRepository' => 'App\\Repository\\DisponibiliteRepository',
            'manager' => '?',
            'service' => 'App\\Entity\\Service',
        ]);
    }
}
