<?php

namespace ContainerXP1gF3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DpVyDzJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dpVyDzJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dpVyDzJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'disponibiliteRepository' => ['privates', 'App\\Repository\\DisponibiliteRepository', 'getDisponibiliteRepositoryService', true],
        ], [
            'disponibiliteRepository' => 'App\\Repository\\DisponibiliteRepository',
        ]);
    }
}
