<?php

namespace ContainerXP1gF3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6El6p90Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6El6p90' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6El6p90'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'accredPro' => ['privates', '.errored..service_locator.6El6p90.App\\Entity\\AccreditationPro', NULL, 'Cannot autowire service ".service_locator.6El6p90": it needs an instance of "App\\Entity\\AccreditationPro" but this type has been excluded in "config/services.yaml".'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'accredPro' => 'App\\Entity\\AccreditationPro',
            'manager' => '?',
        ]);
    }
}
