<?php

namespace ContainerXP1gF3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDisponibiliteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8uNgQhU.App\Entity\Disponibilite' shared service.
     *
     * @return \App\Entity\Disponibilite
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8uNgQhU": it needs an instance of "App\\Entity\\Disponibilite" but this type has been excluded in "config/services.yaml".');
    }
}
