<?php

namespace ContainerXP1gF3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemandes2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.RW.Jqr7.App\Entity\Demandes' shared service.
     *
     * @return \App\Entity\Demandes
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.RW.Jqr7": it needs an instance of "App\\Entity\\Demandes" but this type has been excluded in "config/services.yaml".');
    }
}
