<?php

namespace ContainerXP1gF3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditUserPictureTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\EditUserPictureType' shared autowired service.
     *
     * @return \App\Form\EditUserPictureType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/EditUserPictureType.php';

        return $container->privates['App\\Form\\EditUserPictureType'] = new \App\Form\EditUserPictureType();
    }
}
