<?php

namespace ContainerXP1gF3N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFavoriService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6F7V8Ym.App\Entity\Favori' shared service.
     *
     * @return \App\Entity\Favori
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6F7V8Ym": it needs an instance of "App\\Entity\\Favori" but this type has been excluded in "config/services.yaml".');
    }
}
